language: python
before_script:
    - virtualenv cormoran_env
    - source cormoran_env/bin/activate
    - pip install nose
    - pip install pyhamcrest
    - pip install pydoubles
    - pip install coverage

script:
    - python setup.py develop
    - nosetests tests/unit
