language: python
before_script:
    - virtualenv cormoran_env
    - source cormoran_env/bin/activate
    - pip install --use-mirrors nose pyhamcrest pydoubles

script:
    - python setup.py develop
    - nosetests tests/unit
