language: python
before_script:
    - virtualenv cormoran_env
    - source cormoran_env/bin/activate
    - pip install nose pyhamcrest pydoubles coverage

script:
    python setup.py develop
    nosetests tests/unit
